---
# App Release Version
release_version: 1.0

# App Path
upload_file_url_path: /csvwebapp/upload
get_list_of_files: /csvwebapp/files
download_a_file: /csvwebapp/files/{fileId}

#  Logging information
version: 1
formatters:
  simple:
    format: "[%(asctime)s] {%(module)s:%(lineno)d} %(levelname)s: %(message)s"
  extended:
    format: "[%(asctime)s] {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple


  file_handler:
    class: logging.FileHandler
    level: INFO
    filename: csvwebapp.log
    formatter: extended

loggers:
  dev:
    level: INFO
    handlers: [console,file_handler]
  test:
    level: INFO
    handlers: [console]

root:
  level: INFO
  handlers: [console,file_handler]